### ISSUE TITLE
使用二维码扫描的方式，测试软件

### ISSUE THREAD

**Issue by EricLi404** [608emenu/emenu#19]
## 需要测试的内容，
- 软件在 IOS 和安卓上运行效果区别；
- 走一下整个订单流程，对比一下后台获取到的数据是否相同；

![Markdown](http://i1.piimg.com/1949/eb948b632b09b537.png)

**Comment by FFFfffyb** [comment]
订单无法保存到数据库

**Comment by FFFfffyb** [comment]
订单内容，备注信息无法显示
